create table if not exists public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null check (char_length(name) between 2 and 100),
    phone text not null check (char_length(phone) between 8 and 40),
    subject text not null check (char_length(subject) between 2 and 120),
    message text not null check (char_length(message) between 2 and 2500),
    source text not null default 'site',
    status text not null default 'novo' check (status in ('novo', 'contatado', 'qualificado', 'arquivado'))
);

alter table public.leads enable row level security;
revoke all on table public.leads from anon, authenticated;
grant select, insert, update on table public.leads to service_role;
grant usage, select on sequence public.leads_id_seq to service_role;

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_status_idx on public.leads (status);
